### ISSUE TITLE
Determining the features implemented for Final Milestone

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#235]
We are approaching the end of our project but we don't have enough time to implement all of the requirements in time. Because of this, we need to prioritize some of the requirements while neglecting others. In brief, remaining features are:

### Critical:

- [x] - Advanced search with dynamic filter/query creation based on data fields.
- [x] - Retrieving and presenting location data from/to user with dynamic maps.
- [x] - User profiles
- [x] - Editing/ deleting posts.

### Important:

- [ ] -  Privacy options
- [x] #246
- [ ] - Semantic tagging configuration.
- [x] - Activity Streams 

### Secondary:

- [x] - Liking, commenting on posts
- [x] - File uploading and sharing.

**Comment by gktpmuhammed** [comment]
The location feature is added. You can find related [issue](https://github.com/bounswe/2021SpringGroup1/issues/239) and [PR](https://github.com/bounswe/2021SpringGroup1/pull/242) in provided links.

**Comment by emrahdgn** [comment]
Deleting Post endpoint is implemented in Backend endpoints. I tried Editing Post endpoint but i couldn't finish it because it is much more complicated and hard due to dynamic features.

**Comment by emrahdgn** [comment]
User Profile endpoint is added in Backend endpoints. For now there is no profile picture field because we did not add profile picture link field in the User model. In later, we will try to add this field to the User model and endpoint

**Comment by 4teko7** [comment]
Backend implemented the advanced filter for community posts. I will implement it in the frontend. Beside this, profile info will be implemented as well.

**Comment by emiroztoprak** [comment]
I'm focusing on the editing and deleting posts in frontend. Only the creator of a post or the moderator of the community should be able to delete a post.

**Comment by yunus-topal** [comment]
I added 
- new data types for post creation and post template creation. 
- post creation feature (it does not work on location type)
i also updated post viewing and now we can see every data type on post view.
I couldn't finish advanced search but instead of that, there is a basic version of it which is picking specific post template and passing a search keyword on it.

**Comment by gktpmuhammed** [comment]
I have added commenting functionalities. You can find related [issue](https://github.com/bounswe/2021SpringGroup1/issues/261) and [PR](https://github.com/bounswe/2021SpringGroup1/pull/274) respectively.

**Comment by MrLebowski42** [comment]
It is a bit late but I have implemented the advanced search/filtering API functionality as well as editing post endpoint. File upload is also supported and user profile endpoint is fixed.

**Comment by MrLebowski42** [comment]
We have created the [release](https://github.com/bounswe/2021SpringGroup1/releases/tag/v0.9) so I'm closing this issue.
